apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wordpress-{{ .Values.namespace }}
  hostPath:
    path: /mnt/project/wp-data-{{ .Values.namespace }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: wordpress-{{ .Values.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.2.1-apache
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service.{{ .Values.namespace }}.svc.cluster.local
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: mysql
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc-{{ .Values.namespace }}

---              
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default (randInt 30000 32767) }}
